apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pod-label-webhook
    app.kubernetes.io/part-of: pod-label-webhook
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
imagePullSecrets:
  - name: my-docker-registry

---
apiVersion: v1
kind: Secret
metadata:
  name: my-docker-registry
  namespace: system
data:
# TODO: Update the docker secret
  .dockerconfigjson: <your_docker_secret>
type: kubernetes.io/dockerconfigjson
